version: '3.9'
services:
  express:
    container_name: fin_express
    restart: always
    build: .
    ports:
      - "5000:3333"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: fin_mongo
    image: mongo
    ports:
      - "27017:27017"
